version: '2'

services:
  #redmine
  redmine-postgresql:
    image: sameersbn/postgresql:9.6-2
    restart: always
    environment:
      - DB_USER=redmine
      - DB_PASS=123456
      - DB_NAME=redmine_production
    volumes:
      - /srv/docker/redmine/postgresql:/var/lib/postgresql

  redmine:
    image: sameersbn/redmine:3.4.2
    restart: always
    depends_on:
      - redmine-postgresql
    environment:
      - TZ=Asia/Shanghai

      - DB_ADAPTER=postgresql
      - DB_HOST=redmine-postgresql
      - DB_PORT=5432
      - DB_USER=redmine
      - DB_PASS=123456
      - DB_NAME=redmine_production

      - REDMINE_PORT=
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=/redmine
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=false
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=123456
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=123456
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

    ports:
      - "10083:80"
    volumes:
      - /srv/docker/redmine/redmine:/home/redmine/data

  #gitlab
  gitlab-redis:
    restart: always
    image: sameersbn/redis:latest
    command:
      - --loglevel warning
    volumes:
      - /srv/docker/gitlab/redis:/var/lib/redis:Z

  gitlab-postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
      - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
      - DB_USER=gitlab
      - DB_PASS=123456
      - DB_NAME=gitlabhq_production
      - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:10.1.3
    depends_on:
      - gitlab-redis
      - gitlab-postgresql
    ports:
      - "10184:22"
      - "10185:80"
    volumes:
      - /srv/docker/gitlab/gitlab:/home/git/data:Z
    environment:
      - DEBUG=false

      - DB_ADAPTER=postgresql
      - DB_HOST=gitlab-postgresql
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=123456
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=gitlab-redis
      - REDIS_PORT=6379

      - TZ=Asia/Shanghai
      - GITLAB_TIMEZONE=Beijing

      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false

      - GITLAB_HOST=127.0.0.1 # project path
      - GITLAB_PORT=10182 # http port
      - GITLAB_SSH_PORT=10183 # ssh port
      - GITLAB_RELATIVE_URL_ROOT=/gitlab
      - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
      - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string

      - GITLAB_ROOT_PASSWORD=123456
      - GITLAB_ROOT_EMAIL=marcuse.ye@outlook.com

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_EMAIL=notifications@example.com
      - GITLAB_EMAIL_REPLY_TO=noreply@example.com
      - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

      - GITLAB_BACKUP_SCHEDULE=weekly
      - GITLAB_BACKUP_TIME=01:00
      # - AWS_BACKUPS=true
      # - AWS_BACKUP_REGION=us-east-1
      # - AWS_BACKUP_BUCKET=xxxxxxxxxx-bucket
      # - AWS_BACKUP_ACCESS_KEY_ID=xxxxxxxxxxx
      # - AWS_BACKUP_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxx

      - SMTP_ENABLED=false
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=123456
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=123456
      - IMAP_SSL=true
      - IMAP_STARTTLS=false

      - OAUTH_ENABLED=false
      - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
      - OAUTH_ALLOW_SSO=
      - OAUTH_BLOCK_AUTO_CREATED_USERS=true
      - OAUTH_AUTO_LINK_LDAP_USER=false
      - OAUTH_AUTO_LINK_SAML_USER=false
      - OAUTH_EXTERNAL_PROVIDERS=

      - OAUTH_CAS3_LABEL=cas3
      - OAUTH_CAS3_SERVER=
      - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
      - OAUTH_CAS3_LOGIN_URL=/cas/login
      - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
      - OAUTH_CAS3_LOGOUT_URL=/cas/logout

      - OAUTH_GOOGLE_API_KEY=
      - OAUTH_GOOGLE_APP_SECRET=
      - OAUTH_GOOGLE_RESTRICT_DOMAIN=

      - OAUTH_FACEBOOK_API_KEY=
      - OAUTH_FACEBOOK_APP_SECRET=

      - OAUTH_TWITTER_API_KEY=
      - OAUTH_TWITTER_APP_SECRET=

      - OAUTH_GITHUB_API_KEY=
      - OAUTH_GITHUB_APP_SECRET=
      - OAUTH_GITHUB_URL=
      - OAUTH_GITHUB_VERIFY_SSL=

      - OAUTH_GITLAB_API_KEY=
      - OAUTH_GITLAB_APP_SECRET=

      - OAUTH_BITBUCKET_API_KEY=
      - OAUTH_BITBUCKET_APP_SECRET=

      - OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=
      - OAUTH_SAML_IDP_CERT_FINGERPRINT=
      - OAUTH_SAML_IDP_SSO_TARGET_URL=
      - OAUTH_SAML_ISSUER=
      - OAUTH_SAML_LABEL="Our SAML Provider"
      - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=urn:oasis:names:tc:SAML:2.0:nameid-format:transient
      - OAUTH_SAML_GROUPS_ATTRIBUTE=
      - OAUTH_SAML_EXTERNAL_GROUPS=
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
      - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

      - OAUTH_CROWD_SERVER_URL=
      - OAUTH_CROWD_APP_NAME=
      - OAUTH_CROWD_APP_123456=

      - OAUTH_AUTH0_CLIENT_ID=
      - OAUTH_AUTH0_CLIENT_SECRET=
      - OAUTH_AUTH0_DOMAIN=

      - OAUTH_AZURE_API_KEY=
      - OAUTH_AZURE_API_SECRET=
      - OAUTH_AZURE_TENANT_ID=

  # jenkins  
  # jenkins:
  #   image: jenkins:latest
  #   restart: always
  #   environment:
  #     - JENKINS_OPTS=--prefix=/jenkins
  #     - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
  #   volumes:
  #     - /srv/docker/jenkins/jenkins:/var/jenkins_home

  # proxy
  proxy:
    build: ./proxy
    image: proxy
    links:
      - gitlab:gitlab
      - redmine:redmine
      - jenkins:jenkins
    ports:
      - "80:80"

  # showdoc
  showdoc:
    build: ./showdoc
    image: showdoc
    restart: always
    ports:
      - "9000:80"
    volumes:
      - /srv/docker/showdoc/showdoc:/var/www/html/showdoc:Z
  # nexus
  # nexus:
  #   image: sonatype/nexus3:3.13.0
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #     - "8082:8082"
  #     - "8083:8083"
  #   volumes:
  #     - /srv/docker/nexus/nexus-data:/nexus-data:Z
  #   environment:
  #     - NEXUS_CONTEXT=nexus




#gitlab-mirrors
  # gitlab-mirrors:
  # build: ./docker-gitlab-mirrors
  # image: gitlab-mirrors
  # volumes:
  #   - /srv/docker/gitlab-mirrors/config:/config:Z
  #   - /srv/docker/gitlab-mirrors/data:/data:Z
  # depends_on:
  #   - gitlab-redis
  #   - gitlab-postgresql
  # environment:
  #   - GITLAB_MIRROR_UID=1000
  #   - GITLAB_MIRROR_GITLAB_USER=user
  #   - GITLAB_MIRROR_GITLAB_NAMESPACE=group
  #   - GITLAB_MIRROR_GITLAB_URL=http://host:port/gitlab
